apiVersion: skaffold/v1beta2
kind: config
build: 
    local: 
        push: false
    artifcats: 
        - image: 23david73/multi-client
            context: client
            docker: 
                dockerfile: Dockerfile.dev
        sync: 
            '**/*.js': .
            '**/*.css': .
            '**/*.html': .
        - image: 23david73/multi-server
            context: server
            docker: 
                dockerfile: Dockerfile.dev
        sync: 
            '**/*.js': .
deploy: 
deploy: 
    kubectl: 
        manifests: 
            - k8s/client-deployment.yaml
